site_name: 'sysco-python-app-1'
site_description: 'Main documentation for sysco-python-app-1'
repo_url: https://github.com/kezri-29/sysco-python-app-1
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  # - redirects:
  #     redirect_maps:
  #       'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting Started: 'docs/index.md'